
INSERT INTO `noticias` (`titulo`, `cuerpo`, `url`, `sitio`) VALUES
( 'Vacunas contra Covid-19 llegarán mañana', 'El Ministerio de Salud indicó que las vacunas de Pfizer para contener la Covid-19, llegarán al país mañana, miércoles 20 de enero. ', 'https://www.lahora.com.ec/noticia/1102338550/vacunas-contra-covid-19-llegaran-manana-', 'lahora'),
( 'Aeropuerto de Quito tiene todo listo para recibir las vacunas contra el Covid-19', 'A partir del 18 de enero, se prevé que arribe al país una parte de las 86.000 dosis de la vacuna contra el Covid-19. Serán aplicadas en el personal sanitario y en adultos mayores. ', 'https://www.primicias.ec/noticias/sociedad/aeropuerto-quito-vacunas-dosis-covid/ ', 'primicias'),
( 'Municipio de Quito alista 2 compras para pruebas de covid-19', 'En Quito hay un incremento exponencial de casos de covid-19. En las dos primeras semanas de enero se duplicaron los contagios y se incrementaron la positividad y la reproductividad del virus.', 'https://www.elcomercio.com/actualidad/quito-compras-pruebas-covid-contagio.html', 'elcomercio'),
( 'Ecuador alcanza 231.644 contagios y 14.332 decesos acumulados por la covid-19', 'Ecuador llegó este lunes a 231.644 positivos acumulados del coronavirus SARS-CoV-2, incrementando 162 contagios en las últimas 24 horas, mientras que los fallecidos por la covid-19 sumaron 14.332', 'https://ww2.elmercurio.com.ec/2021/01/18/ecuador-alcanza-231-644-contagios-y-14-332-decesos-acumulados-por-la-covid-19/?utm_source=rss&utm_medium=rss&utm_campaign=ecuador-alcanza-231-644-contagios-y-14-332-decesos-acumulados-por-la-covid-19', 'elmercurio'),
( 'Quito: Un clic para informarte sobre la Covid-19', 'La Secretaría de Salud de Quito tiene una plataforma virtual de información sobre cómo protegerse de la Covid-19 y cómo cuidar la salud mental durante estos tiempos difíciles.', 'https://lahora.com.ec/noticia/1102336578/quito-un-clic-para-informarte-sobre-la-covid-19', 'lahora'),
( 'Mortalidad por covid-19 preocupa a autoridades de Guayaquil.', 'Guayaquil registra un aumento de defunciones. 285 personas murieron la semana pasada, por diversas causas. De ellas, 70 fallecieron con diagnóstico de coronavirus de acuerdo con los reportes del Comité de Operaciones de Emergencia (COE) cantonal.', 'https://www.elcomercio.com/actualidad/mortalidad-covid-guayaquil-pandemia-fallecidos.html. ', 'elcomercio'),
( 'Quito: Salvoconductos otorgados por el municipio quedan suspendidos', 'El Municipio de Quito informó mediante la Secretaría de Movilidad que los salvoconductos emitidos en Quito desde el 14 de septiembre hasta el 22 de diciembre quedan suspendidos hasta una nueva disposición del COE Nacional', 'https://www.eluniverso.com/noticias/2020/12/23/nota/8716897/quito-salvoconductos-otorgados-municipio-quedan-suspendidos', 'eluniverso'),
( 'Cero salidas nocturnas por 15 días', 'El Gobierno nacional decretó un nuevo estado de excepción que rige desde el 21 de diciembre del 2020 y que se extenderá durante 30 días. Esta es una de las nueve disposiciones anunciadas por el presidente', 'https://www.ultimasnoticias.ec/las-ultimas/excepcion-ecuador-navidad-covid.html', 'ultimasnoticias');



COMMIT;
